# Generated by Django 4.0.1 on 2022-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
            ],
            options={
                'db_table': 'projectify_projects',
            },
        ),
    ]
